/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const addressCountryMax = 2;

export const Address = zod.object({
  id: zod.uuid().nullable(),
  addressLine1: zod.string(),
  addressLine2: zod.string().nullish(),
  addressLine3: zod.string().nullish(),
  addressLine4: zod.string().nullish(),
  townOrCity: zod.string().nullish(),
  postCode: zod.string().nullish(),
  county: zod.string().nullish(),
  country: zod.string().max(addressCountryMax),
  createdAt: zod.iso.datetime({ offset: true }).nullable(),
  modifiedAt: zod.iso.datetime({ offset: true }).nullable(),
});

export type Address = zod.input<typeof Address>;
export type AddressOutput = zod.output<typeof Address>;
