/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ApplicationScopingQuestions = zod.object({
  priorLegalAid: zod
    .enum(["no", "yesDifferentMatter", "yesSameMatter"])
    .optional(),
  familyLawClassification: zod.enum(["public", "private"]).optional(),
  needsAdviceOnEUOrInternationalMaintenance: zod.boolean().optional(),
});

export type ApplicationScopingQuestions = zod.input<
  typeof ApplicationScopingQuestions
>;
export type ApplicationScopingQuestionsOutput = zod.output<
  typeof ApplicationScopingQuestions
>;
