/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const applicationClientDetailsNiNumberMin = 9;
export const applicationClientDetailsNiNumberMax = 9;

export const applicationClientDetailsNiNumberRegExp = new RegExp(
  "[A-CEGHJ-NOPR-TW-Z]{2}[0-9]{6}[ABCDs]{1}",
);
export const applicationClientDetailsAddressOneCountryMax = 2;

export const Application = zod.object({
  id: zod.uuid(),
  applicationRefNumber: zod.string().nullish(),
  individualLegalAidNumber: zod.uuid(),
  providerFirmCode: zod.string(),
  providerOfficeCode: zod.string(),
  meansAssessmentId: zod.uuid().nullish(),
  clientDetails: zod.object({
    id: zod.uuid().nullable(),
    firstName: zod.string(),
    lastName: zod.string(),
    dateOfBirth: zod.iso.date(),
    niNumber: zod
      .string()
      .min(applicationClientDetailsNiNumberMin)
      .max(applicationClientDetailsNiNumberMax)
      .regex(applicationClientDetailsNiNumberRegExp)
      .nullish(),
    hasFixedAddress: zod.boolean(),
    address: zod
      .union([
        zod.object({
          id: zod.uuid().nullable(),
          addressLine1: zod.string(),
          addressLine2: zod.string().nullish(),
          addressLine3: zod.string().nullish(),
          addressLine4: zod.string().nullish(),
          townOrCity: zod.string().nullish(),
          postCode: zod.string().nullish(),
          county: zod.string().nullish(),
          country: zod
            .string()
            .max(applicationClientDetailsAddressOneCountryMax),
          createdAt: zod.iso.datetime({ offset: true }).nullable(),
          modifiedAt: zod.iso.datetime({ offset: true }).nullable(),
        }),
        zod.null(),
      ])
      .optional(),
    createdAt: zod.iso.datetime({ offset: true }).nullable(),
    modifiedAt: zod.iso.datetime({ offset: true }).nullable(),
  }),
  applicationState: zod.enum(["DRAFT", "COMPLETED"]),
  declaration: zod.union([
    zod.object({
      id: zod.uuid().nullable(),
      declarationConfirmation: zod.boolean().nullable(),
      dateSigned: zod.iso.date().nullish(),
      createdAt: zod.iso.datetime({ offset: true }).nullable(),
      createdBy: zod.string().nullable(),
      modifiedAt: zod.iso.datetime({ offset: true }).nullable(),
      modifiedBy: zod.string().nullable(),
    }),
    zod.null(),
  ]),
  evidence: zod.union([
    zod.object({
      evidenceExemptionCode: zod.string().nullish(),
      evidenceExemptionReason: zod.string().nullish(),
      incomeEvidenceChecklist: zod.looseObject({}).nullish(),
      expenditureCapitalEvidenceChecklist: zod.looseObject({}).nullish(),
    }),
    zod.null(),
  ]),
  eligibility: zod.union([
    zod.object({
      data: zod.looseObject({}).nullish(),
      result: zod.looseObject({}).nullable(),
    }),
    zod.null(),
  ]),
  reasonForReapplication: zod.string().nullish(),
  meansAssessmentRequired: zod.boolean().nullish(),
  typeOfNonMeans: zod.boolean().nullish(),
  contribution: zod.string().nullish(),
  scopingQuestions: zod.looseObject({}).nullish(),
  applicationType: zod.string(),
  createdAt: zod.iso.datetime({ offset: true }),
  createdBy: zod.string(),
  modifiedAt: zod.iso.datetime({ offset: true }),
  modifiedBy: zod.string(),
});

export type Application = zod.input<typeof Application>;
export type ApplicationOutput = zod.output<typeof Application>;
