/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const applicationClientDetailsNiNumberMin = 9;
export const applicationClientDetailsNiNumberMax = 9;

export const applicationClientDetailsNiNumberRegExp = new RegExp(
  "[A-CEGHJ-NOPR-TW-Z]{2}[0-9]{6}[ABCDs]{1}",
);
export const applicationClientDetailsAddressOneCountryMax = 2;

export const Application = zod.object({
  id: zod.uuid(),
  applicationRefNumber: zod.string().nullish(),
  individualLegalAidNumber: zod.uuid(),
  providerFirmCode: zod.string(),
  providerOfficeCode: zod.string(),
  meansAssessmentId: zod.uuid().nullish(),
  clientDetails: zod.object({
    id: zod.uuid().nullish(),
    firstName: zod.string(),
    lastName: zod.string(),
    dateOfBirth: zod.iso.date(),
    niNumber: zod
      .string()
      .min(applicationClientDetailsNiNumberMin)
      .max(applicationClientDetailsNiNumberMax)
      .regex(applicationClientDetailsNiNumberRegExp)
      .nullish(),
    hasFixedAddress: zod.boolean(),
    address: zod
      .union([
        zod.object({
          id: zod.uuid().nullish(),
          addressLine1: zod.string(),
          addressLine2: zod.string().nullish(),
          addressLine3: zod.string().nullish(),
          addressLine4: zod.string().nullish(),
          townOrCity: zod.string().nullish(),
          postCode: zod.string().nullish(),
          county: zod.string().nullish(),
          country: zod
            .string()
            .max(applicationClientDetailsAddressOneCountryMax),
          createdAt: zod.iso.datetime({ offset: true }).nullish(),
          modifiedAt: zod.iso.datetime({ offset: true }).nullish(),
        }),
        zod.null(),
      ])
      .optional(),
    createdAt: zod.iso.datetime({ offset: true }).nullish(),
    modifiedAt: zod.iso.datetime({ offset: true }).nullish(),
  }),
  applicationState: zod.enum(["DRAFT", "COMPLETED"]),
  declaration: zod
    .union([
      zod.object({
        id: zod.uuid().nullish(),
        declarationConfirmation: zod.boolean().nullish(),
        dateSigned: zod.iso.date().nullish(),
        createdAt: zod.iso.datetime({ offset: true }).nullish(),
        createdBy: zod.string().nullish(),
        modifiedAt: zod.iso.datetime({ offset: true }).nullish(),
        modifiedBy: zod.string().nullish(),
      }),
      zod.null(),
    ])
    .optional(),
  evidence: zod
    .union([
      zod.object({
        evidenceExemptionCode: zod.string().nullish(),
        evidenceExemptionReason: zod.string().nullish(),
        incomeEvidenceChecklist: zod.looseObject({}).nullish(),
        expenditureCapitalEvidenceChecklist: zod.looseObject({}).nullish(),
      }),
      zod.null(),
    ])
    .optional(),
  eligibility: zod
    .union([
      zod.object({
        data: zod.looseObject({}).nullish(),
        result: zod.looseObject({}).nullish(),
      }),
      zod.null(),
    ])
    .optional(),
  reasonForReapplication: zod.string().nullish(),
  meansAssessmentRequired: zod.boolean().nullish(),
  typeOfNonMeans: zod.boolean().nullish(),
  contribution: zod.string().nullish(),
  scopingQuestions: zod.looseObject({}).nullish(),
  applicationType: zod.string(),
  createdAt: zod.iso.datetime({ offset: true }),
  createdBy: zod.string(),
  modifiedAt: zod.iso.datetime({ offset: true }),
  modifiedBy: zod.string(),
});

export type Application = zod.input<typeof Application>;
export type ApplicationOutput = zod.output<typeof Application>;
