/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const Applications = zod.array(
  zod.object({
    id: zod.uuid(),
    name: zod.string(),
    applicationRefNumber: zod.string(),
    modifiedAt: zod.iso.datetime({ offset: true }),
    eligibilityIndication: zod.union([
      zod.enum(["eligible", "ineligible"]),
      zod.null(),
    ]),
  }),
);

export type Applications = zod.input<typeof Applications>;
export type ApplicationsOutput = zod.output<typeof Applications>;
