/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ApplicationStatus = zod.enum(["DRAFT", "COMPLETE"]);

export type ApplicationStatus = zod.input<typeof ApplicationStatus>;
export type ApplicationStatusOutput = zod.output<typeof ApplicationStatus>;
