/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ApplicationState = zod.enum(["DRAFT", "COMPLETED"]);

export type ApplicationState = zod.input<typeof ApplicationState>;
export type ApplicationStateOutput = zod.output<typeof ApplicationState>;
