/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const clientDetailsNiNumberMin = 9;
export const clientDetailsNiNumberMax = 9;

export const clientDetailsNiNumberRegExp = new RegExp(
  "[A-CEGHJ-NOPR-TW-Z]{2}[0-9]{6}[ABCDs]{1}",
);
export const clientDetailsAddressCountryMax = 2;

export const ClientDetails = zod.object({
  id: zod.uuid().optional(),
  firstName: zod.string(),
  lastName: zod.string(),
  dateOfBirth: zod.iso.date(),
  niNumber: zod
    .string()
    .min(clientDetailsNiNumberMin)
    .max(clientDetailsNiNumberMax)
    .regex(clientDetailsNiNumberRegExp)
    .optional(),
  hasFixedAddress: zod.boolean(),
  address: zod
    .object({
      id: zod.uuid().optional(),
      addressLine1: zod.string(),
      addressLine2: zod.string().optional(),
      addressLine3: zod.string().optional(),
      addressLine4: zod.string().optional(),
      townOrCity: zod.string().optional(),
      postCode: zod.string().optional(),
      county: zod.string().optional(),
      country: zod.string().max(clientDetailsAddressCountryMax),
      createdAt: zod.iso.datetime({ offset: true }).optional(),
      modifiedAt: zod.iso.datetime({ offset: true }).optional(),
    })
    .optional(),
  createdAt: zod.iso.datetime({ offset: true }).optional(),
  modifiedAt: zod.iso.datetime({ offset: true }).optional(),
});

export type ClientDetails = zod.input<typeof ClientDetails>;
export type ClientDetailsOutput = zod.output<typeof ClientDetails>;
