/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const clientDetailsNiNumberMin = 9;
export const clientDetailsNiNumberMax = 9;

export const clientDetailsNiNumberRegExp = new RegExp(
  "[A-CEGHJ-NOPR-TW-Z]{2}[0-9]{6}[ABCDs]{1}",
);
export const clientDetailsAddressOneCountryMax = 2;

export const ClientDetails = zod.object({
  id: zod.uuid().nullable(),
  firstName: zod.string(),
  lastName: zod.string(),
  dateOfBirth: zod.iso.date(),
  niNumber: zod
    .string()
    .min(clientDetailsNiNumberMin)
    .max(clientDetailsNiNumberMax)
    .regex(clientDetailsNiNumberRegExp)
    .nullish(),
  hasFixedAddress: zod.boolean(),
  address: zod
    .union([
      zod.object({
        id: zod.uuid().nullable(),
        addressLine1: zod.string(),
        addressLine2: zod.string().nullish(),
        addressLine3: zod.string().nullish(),
        addressLine4: zod.string().nullish(),
        townOrCity: zod.string().nullish(),
        postCode: zod.string().nullish(),
        county: zod.string().nullish(),
        country: zod.string().max(clientDetailsAddressOneCountryMax),
        createdAt: zod.iso.datetime({ offset: true }).nullable(),
        modifiedAt: zod.iso.datetime({ offset: true }).nullable(),
      }),
      zod.null(),
    ])
    .optional(),
  createdAt: zod.iso.datetime({ offset: true }).nullable(),
  modifiedAt: zod.iso.datetime({ offset: true }).nullable(),
});

export type ClientDetails = zod.input<typeof ClientDetails>;
export type ClientDetailsOutput = zod.output<typeof ClientDetails>;
