/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const createClientDetailsRequestBodyNiNumberMin = 9;
export const createClientDetailsRequestBodyNiNumberMax = 9;

export const createClientDetailsRequestBodyNiNumberRegExp = new RegExp(
  "[A-CEGHJ-NOPR-TW-Z]{2}[0-9]{6}[ABCDs]{1}",
);
export const createClientDetailsRequestBodyAddressCountryMax = 2;

export const CreateClientDetailsRequestBody = zod.object({
  firstName: zod.string(),
  lastName: zod.string(),
  dateOfBirth: zod.iso.date(),
  niNumber: zod
    .string()
    .min(createClientDetailsRequestBodyNiNumberMin)
    .max(createClientDetailsRequestBodyNiNumberMax)
    .regex(createClientDetailsRequestBodyNiNumberRegExp)
    .optional(),
  hasFixedAddress: zod.boolean(),
  address: zod
    .object({
      addressLine1: zod.string(),
      addressLine2: zod.string().optional(),
      addressLine3: zod.string().optional(),
      addressLine4: zod.string().optional(),
      townOrCity: zod.string().optional(),
      postCode: zod.string().optional(),
      county: zod.string().nullish(),
      country: zod
        .string()
        .max(createClientDetailsRequestBodyAddressCountryMax),
    })
    .optional(),
});

export type CreateClientDetailsRequestBody = zod.input<
  typeof CreateClientDetailsRequestBody
>;
export type CreateClientDetailsRequestBodyOutput = zod.output<
  typeof CreateClientDetailsRequestBody
>;
