/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const CreateScopingQuestions = zod.object({
  priorLegalAid: zod.enum(["no", "yesDifferentMatter", "yesSameMatter"]),
  familyLawClassification: zod
    .union([zod.enum(["public", "private"]), zod.null()])
    .optional(),
  needsAdviceOnEUOrInternationalMaintenance: zod.boolean().nullish(),
});

export type CreateScopingQuestions = zod.input<typeof CreateScopingQuestions>;
export type CreateScopingQuestionsOutput = zod.output<
  typeof CreateScopingQuestions
>;
