/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const createAddressRequestBodyCountryMax = 2;

export const CreateAddressRequestBody = zod.object({
  addressLine1: zod.string(),
  addressLine2: zod.string().optional(),
  addressLine3: zod.string().optional(),
  addressLine4: zod.string().optional(),
  townOrCity: zod.string().optional(),
  postCode: zod.string().optional(),
  county: zod.string().nullish(),
  country: zod.string().max(createAddressRequestBodyCountryMax),
});

export type CreateAddressRequestBody = zod.input<
  typeof CreateAddressRequestBody
>;
export type CreateAddressRequestBodyOutput = zod.output<
  typeof CreateAddressRequestBody
>;
