/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const CreateApplicationResponseBody = zod.object({
  id: zod.uuid().optional(),
  ecfFlag: zod.boolean().optional(),
  legalAidBefore: zod.string().optional(),
  legalAidLast6Months: zod.boolean().optional(),
  reasonForReapplication: zod.string().optional(),
  clientDetails: zod
    .object({
      id: zod.uuid().optional(),
      firstName: zod.string(),
      lastName: zod.string(),
      dateOfBirth: zod.iso.date(),
      niNumber: zod.string().optional(),
      hasFixedAddress: zod.boolean(),
      address: zod
        .object({
          id: zod.uuid().optional(),
          addressLine1: zod.string(),
          addressLine2: zod.string().optional(),
          addressLine3: zod.string().optional(),
          addressLine4: zod.string().optional(),
          townOrCity: zod.string().optional(),
          postCode: zod.string().optional(),
          county: zod.string().optional(),
          country: zod.string(),
          createdAt: zod.iso.datetime({ offset: true }).optional(),
          modifiedAt: zod.iso.datetime({ offset: true }).optional(),
        })
        .optional(),
      createdAt: zod.iso.datetime({ offset: true }).optional(),
      modifiedAt: zod.iso.datetime({ offset: true }).optional(),
    })
    .optional(),
});

export type CreateApplicationResponseBody = zod.input<
  typeof CreateApplicationResponseBody
>;
export type CreateApplicationResponseBodyOutput = zod.output<
  typeof CreateApplicationResponseBody
>;
