/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const createApplicationRequestBodyClientDetailsNiNumberMin = 9;
export const createApplicationRequestBodyClientDetailsNiNumberMax = 9;

export const createApplicationRequestBodyClientDetailsNiNumberRegExp =
  new RegExp("[A-CEGHJ-NOPR-TW-Z]{2}[0-9]{6}[ABCDs]{1}");
export const createApplicationRequestBodyClientDetailsAddressOneCountryMax = 2;

export const CreateApplicationRequestBody = zod.object({
  legalAidBefore: zod.string(),
  legalAidLast6Months: zod.boolean().optional(),
  reasonForReapplication: zod.string().optional(),
  providerOfficeCode: zod.string(),
  scopingQuestions: zod.record(zod.string(), zod.unknown()),
  clientDetails: zod.object({
    id: zod.uuid().nullish(),
    firstName: zod.string(),
    lastName: zod.string(),
    dateOfBirth: zod.iso.date(),
    niNumber: zod
      .string()
      .min(createApplicationRequestBodyClientDetailsNiNumberMin)
      .max(createApplicationRequestBodyClientDetailsNiNumberMax)
      .regex(createApplicationRequestBodyClientDetailsNiNumberRegExp)
      .nullish(),
    hasFixedAddress: zod.boolean(),
    address: zod
      .union([
        zod.object({
          id: zod.uuid().nullish(),
          addressLine1: zod.string(),
          addressLine2: zod.string().nullish(),
          addressLine3: zod.string().nullish(),
          addressLine4: zod.string().nullish(),
          townOrCity: zod.string().nullish(),
          postCode: zod.string().nullish(),
          county: zod.string().nullish(),
          country: zod
            .string()
            .max(createApplicationRequestBodyClientDetailsAddressOneCountryMax),
          createdAt: zod.iso.datetime({ offset: true }).nullish(),
          modifiedAt: zod.iso.datetime({ offset: true }).nullish(),
        }),
        zod.null(),
      ])
      .optional(),
    createdAt: zod.iso.datetime({ offset: true }).nullish(),
    modifiedAt: zod.iso.datetime({ offset: true }).nullish(),
  }),
});

export type CreateApplicationRequestBody = zod.input<
  typeof CreateApplicationRequestBody
>;
export type CreateApplicationRequestBodyOutput = zod.output<
  typeof CreateApplicationRequestBody
>;
