/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const CreateApplicationResponseBody = zod.object({
  id: zod.uuid(),
});

export type CreateApplicationResponseBody = zod.input<
  typeof CreateApplicationResponseBody
>;
export type CreateApplicationResponseBodyOutput = zod.output<
  typeof CreateApplicationResponseBody
>;
