/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const createApplicationRequestBodyClientDetailsNiNumberMin = 9;
export const createApplicationRequestBodyClientDetailsNiNumberMax = 9;

export const createApplicationRequestBodyClientDetailsNiNumberRegExp =
  new RegExp("[A-CEGHJ-NOPR-TW-Z]{2}[0-9]{6}[ABCDs]{1}");
export const createApplicationRequestBodyClientDetailsAddressCountryMax = 2;

export const CreateApplicationRequestBody = zod.object({
  ecfFlag: zod.boolean(),
  legalAidBefore: zod.string(),
  legalAidLast6Months: zod.boolean().optional(),
  reasonForReapplication: zod.string().optional(),
  providerOfficeCode: zod.string(),
  scopingQuestions: zod.record(zod.string(), zod.unknown()),
  clientDetails: zod.object({
    id: zod.uuid().optional(),
    firstName: zod.string(),
    lastName: zod.string(),
    dateOfBirth: zod.iso.date(),
    niNumber: zod
      .string()
      .min(createApplicationRequestBodyClientDetailsNiNumberMin)
      .max(createApplicationRequestBodyClientDetailsNiNumberMax)
      .regex(createApplicationRequestBodyClientDetailsNiNumberRegExp)
      .optional(),
    hasFixedAddress: zod.boolean(),
    address: zod
      .object({
        id: zod.uuid().optional(),
        addressLine1: zod.string(),
        addressLine2: zod.string().optional(),
        addressLine3: zod.string().optional(),
        addressLine4: zod.string().optional(),
        townOrCity: zod.string().optional(),
        postCode: zod.string().optional(),
        county: zod.string().optional(),
        country: zod
          .string()
          .max(createApplicationRequestBodyClientDetailsAddressCountryMax),
        createdAt: zod.iso.datetime({ offset: true }).optional(),
        modifiedAt: zod.iso.datetime({ offset: true }).optional(),
      })
      .optional(),
    createdAt: zod.iso.datetime({ offset: true }).optional(),
    modifiedAt: zod.iso.datetime({ offset: true }).optional(),
  }),
});

export type CreateApplicationRequestBody = zod.input<
  typeof CreateApplicationRequestBody
>;
export type CreateApplicationRequestBodyOutput = zod.output<
  typeof CreateApplicationRequestBody
>;
