/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const createApplicationBodyClientDetailsNiNumberMin = 9;
export const createApplicationBodyClientDetailsNiNumberMax = 9;

export const createApplicationBodyClientDetailsNiNumberRegExp = new RegExp(
  "[A-CEGHJ-NOPR-TW-Z]{2}[0-9]{6}[ABCDs]{1}",
);
export const createApplicationBodyClientDetailsAddressOneCountryMax = 2;

export const CreateApplicationBody = zod.object({
  legalAidBefore: zod.string(),
  legalAidLast6Months: zod.boolean().optional(),
  reasonForReapplication: zod.string().optional(),
  providerOfficeCode: zod.string(),
  scopingQuestions: zod.record(zod.string(), zod.unknown()),
  clientDetails: zod.object({
    id: zod.uuid().nullish(),
    firstName: zod.string(),
    lastName: zod.string(),
    dateOfBirth: zod.iso.date(),
    niNumber: zod
      .string()
      .min(createApplicationBodyClientDetailsNiNumberMin)
      .max(createApplicationBodyClientDetailsNiNumberMax)
      .regex(createApplicationBodyClientDetailsNiNumberRegExp)
      .nullish(),
    hasFixedAddress: zod.boolean(),
    address: zod
      .union([
        zod.object({
          id: zod.uuid().nullish(),
          addressLine1: zod.string(),
          addressLine2: zod.string().nullish(),
          addressLine3: zod.string().nullish(),
          addressLine4: zod.string().nullish(),
          townOrCity: zod.string().nullish(),
          postCode: zod.string().nullish(),
          county: zod.string().nullish(),
          country: zod
            .string()
            .max(createApplicationBodyClientDetailsAddressOneCountryMax),
          createdAt: zod.iso.datetime({ offset: true }).nullish(),
          modifiedAt: zod.iso.datetime({ offset: true }).nullish(),
        }),
        zod.null(),
      ])
      .optional(),
    createdAt: zod.iso.datetime({ offset: true }).nullish(),
    modifiedAt: zod.iso.datetime({ offset: true }).nullish(),
  }),
});

export type CreateApplicationBody = zod.input<typeof CreateApplicationBody>;
export type CreateApplicationBodyOutput = zod.output<
  typeof CreateApplicationBody
>;
