/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const EligibilityDataIncome = zod
  .object({
    gross_income: zod.number().nullish(),
    income_frequency: zod.string().nullish(),
    income_tax: zod.number().nullish(),
    income_type: zod.string().nullish(),
    national_insurance: zod.number().nullish(),
  })
  .describe(
    "Sources: income (IncomeForm) / partner_income (PartnerIncomeForm).",
  );

export type EligibilityDataIncome = zod.input<typeof EligibilityDataIncome>;
export type EligibilityDataIncomeOutput = zod.output<
  typeof EligibilityDataIncome
>;
