/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const EligibilityDataBankAccount = zod
  .object({
    account_in_dispute: zod.boolean().nullish(),
    amount: zod.number().nullish(),
  })
  .describe(
    "Sources: assets (ClientAssetsForm) / partner_assets (PartnerAssetsForm).",
  );

export type EligibilityDataBankAccount = zod.input<
  typeof EligibilityDataBankAccount
>;
export type EligibilityDataBankAccountOutput = zod.output<
  typeof EligibilityDataBankAccount
>;
