/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const EligibilityDataBenefit = zod
  .object({
    benefit_amount: zod.number().nullish(),
    benefit_frequency: zod.string().nullish(),
    benefit_type: zod.string().nullish(),
  })
  .describe(
    "Sources: benefit_details (BenefitDetailsForm) / partner_benefit_details (PartnerBenefitDetailsForm).",
  );

export type EligibilityDataBenefit = zod.input<typeof EligibilityDataBenefit>;
export type EligibilityDataBenefitOutput = zod.output<
  typeof EligibilityDataBenefit
>;
