/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const EligibilityDataDependantIncome = zod
  .object({
    amount: zod.number().nullish(),
    frequency: zod.string().nullish(),
  })
  .describe("Sources: dependant_income_details (DependantIncomeDetailsForm).");

export type EligibilityDataDependantIncome = zod.input<
  typeof EligibilityDataDependantIncome
>;
export type EligibilityDataDependantIncomeOutput = zod.output<
  typeof EligibilityDataDependantIncome
>;
