/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const EligibilityIndication = zod.enum(["eligible", "ineligible"]);

export type EligibilityIndication = zod.input<typeof EligibilityIndication>;
export type EligibilityIndicationOutput = zod.output<
  typeof EligibilityIndication
>;
