/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const EligibilityDataVehicle = zod
  .object({
    vehicle_finance: zod.number().nullish(),
    vehicle_in_dispute: zod.boolean().nullish(),
    vehicle_in_regular_use: zod.boolean().nullish(),
    vehicle_over_3_years_ago: zod.boolean().nullish(),
    vehicle_pcp: zod.boolean().nullish(),
    vehicle_value: zod.number().nullish(),
  })
  .describe("Sources: vehicles_details (VehiclesDetailsForm).");

export type EligibilityDataVehicle = zod.input<typeof EligibilityDataVehicle>;
export type EligibilityDataVehicleOutput = zod.output<
  typeof EligibilityDataVehicle
>;
