/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const EligibilityDataProperty = zod
  .object({
    house_in_dispute: zod.boolean().nullish(),
    house_value: zod.number().nullish(),
    inline_owned_with_mortgage: zod.boolean().nullish(),
    mortgage: zod.number().nullish(),
    percentage_owned: zod.int().nullish(),
  })
  .describe(
    "Sources: additional_property_details (AdditionalPropertyDetailsForm) / partner_additional_property_details (PartnerAdditionalPropertyDetailsForm).",
  );

export type EligibilityDataProperty = zod.input<typeof EligibilityDataProperty>;
export type EligibilityDataPropertyOutput = zod.output<
  typeof EligibilityDataProperty
>;
