/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const Eligibility = zod.object({
  data: zod.looseObject({}).nullish(),
  result: zod.looseObject({}).nullish(),
});

export type Eligibility = zod.input<typeof Eligibility>;
export type EligibilityOutput = zod.output<typeof Eligibility>;
