/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const Evidence = zod.object({
  evidenceExemptionCode: zod.string().nullish(),
  evidenceExemptionReason: zod.string().nullish(),
  incomeEvidenceChecklist: zod.looseObject({}).nullish(),
  expenditureCapitalEvidenceChecklist: zod.looseObject({}).nullish(),
});

export type Evidence = zod.input<typeof Evidence>;
export type EvidenceOutput = zod.output<typeof Evidence>;
