/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const FamilyLawClassification = zod.enum(["public", "private"]);

export type FamilyLawClassification = zod.input<typeof FamilyLawClassification>;
export type FamilyLawClassificationOutput = zod.output<
  typeof FamilyLawClassification
>;
