/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const getApplicationsParamsPageDefault = 0;
export const getApplicationsParamsSizeDefault = 25;
export const GetApplicationsParams = zod.object({
  page: zod.number().default(getApplicationsParamsPageDefault),
  size: zod.number().default(getApplicationsParamsSizeDefault),
  officeId: zod.uuid().optional(),
  status: zod.enum(["DRAFT", "COMPLETE"]).optional(),
});

export type GetApplicationsParams = zod.input<typeof GetApplicationsParams>;
export type GetApplicationsParamsOutput = zod.output<
  typeof GetApplicationsParams
>;
