/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const getApplicationsParamsPageDefault = 0;
export const getApplicationsParamsSizeDefault = 25;
export const GetApplicationsParams = zod.object({
  page: zod.int().default(getApplicationsParamsPageDefault),
  size: zod.int().default(getApplicationsParamsSizeDefault),
  officeId: zod.string().optional(),
  status: zod.enum(["DRAFT", "COMPLETED"]).optional(),
});

export type GetApplicationsParams = zod.input<typeof GetApplicationsParams>;
export type GetApplicationsParamsOutput = zod.output<
  typeof GetApplicationsParams
>;
