/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const PriorLegalAid = zod.enum([
  "no",
  "yesDifferentMatter",
  "yesSameMatter",
]);

export type PriorLegalAid = zod.input<typeof PriorLegalAid>;
export type PriorLegalAidOutput = zod.output<typeof PriorLegalAid>;
