/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ScopingQuestions = zod.object({
  priorLegalAid: zod
    .enum(["no", "yesDifferentMatter", "yesSameMatter"])
    .optional(),
});

export type ScopingQuestions = zod.input<typeof ScopingQuestions>;
export type ScopingQuestionsOutput = zod.output<typeof ScopingQuestions>;
