/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const ScopingQuestions = zod.object({
  priorLegalAid: zod.enum(["no", "yesDifferentMatter", "yesSameMatter"]),
  familyLawClassification: zod
    .union([zod.enum(["public", "private"]), zod.null()])
    .optional(),
  needsAdviceOnEUOrInternationalMaintenance: zod.boolean().nullish(),
});

export type ScopingQuestions = zod.input<typeof ScopingQuestions>;
export type ScopingQuestionsOutput = zod.output<typeof ScopingQuestions>;
