/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const updateClientDetailsRequestBodyNiNumberMin = 9;
export const updateClientDetailsRequestBodyNiNumberMax = 9;

export const updateClientDetailsRequestBodyNiNumberRegExp = new RegExp(
  "^(?!BG|GB|KN|NK|NT|TN|ZZ)[A-CEGHJ-PR-TW-Z][A-CEGHJ-NPR-TW-Z][0-9]{6}[ABCD]$",
);
export const updateClientDetailsRequestBodyAddressOneCountryMin = 2;
export const updateClientDetailsRequestBodyAddressOneCountryMax = 2;

export const UpdateClientDetailsRequestBody = zod.object({
  firstName: zod.string(),
  lastName: zod.string(),
  dateOfBirth: zod.iso.date(),
  niNumber: zod
    .string()
    .min(updateClientDetailsRequestBodyNiNumberMin)
    .max(updateClientDetailsRequestBodyNiNumberMax)
    .regex(updateClientDetailsRequestBodyNiNumberRegExp)
    .nullable()
    .describe("Required but nullable; null clears the NI number."),
  hasFixedAddress: zod.boolean().describe("False requires address to be null."),
  address: zod
    .union([
      zod
        .object({
          addressLine1: zod.string(),
          addressLine2: zod.string().nullable(),
          addressLine3: zod.string().nullable(),
          addressLine4: zod.string().nullable(),
          townOrCity: zod.string().nullable(),
          postCode: zod.string().nullable(),
          county: zod.string().nullable(),
          country: zod
            .string()
            .min(updateClientDetailsRequestBodyAddressOneCountryMin)
            .max(updateClientDetailsRequestBodyAddressOneCountryMax),
        })
        .nullable(),
      zod.null(),
    ])
    .describe(
      "Required but nullable; true hasFixedAddress requires an object.",
    ),
});

export type UpdateClientDetailsRequestBody = zod.input<
  typeof UpdateClientDetailsRequestBody
>;
export type UpdateClientDetailsRequestBodyOutput = zod.output<
  typeof UpdateClientDetailsRequestBody
>;
