/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const updateApplicationDetailsBodyClientDetailsNiNumberMin = 9;
export const updateApplicationDetailsBodyClientDetailsNiNumberMax = 9;

export const updateApplicationDetailsBodyClientDetailsNiNumberRegExp =
  new RegExp(
    "^(?!BG|GB|KN|NK|NT|TN|ZZ)[A-CEGHJ-PR-TW-Z][A-CEGHJ-NPR-TW-Z][0-9]{6}[ABCD]$",
  );
export const updateApplicationDetailsBodyClientDetailsAddressOneCountryMin = 2;
export const updateApplicationDetailsBodyClientDetailsAddressOneCountryMax = 2;

export const UpdateApplicationDetailsBody = zod.object({
  priorLegalAid: zod.enum(["no", "yesDifferentMatter", "yesSameMatter"]),
  legalAidLast6Months: zod
    .boolean()
    .describe("Journey answer; not persisted as a separate field."),
  reasonForReapplication: zod
    .string()
    .nullable()
    .describe(
      "Required but nullable. Must be nonblank when legalAidLast6Months is true on the applicable priorLegalAid branch; otherwise it must be null. An empty string is a value, not a clear operation.\n",
    ),
  ecfFlag: zod.boolean(),
  clientDetails: zod.object({
    firstName: zod.string(),
    lastName: zod.string(),
    dateOfBirth: zod.iso.date(),
    niNumber: zod
      .string()
      .min(updateApplicationDetailsBodyClientDetailsNiNumberMin)
      .max(updateApplicationDetailsBodyClientDetailsNiNumberMax)
      .regex(updateApplicationDetailsBodyClientDetailsNiNumberRegExp)
      .nullable()
      .describe("Required but nullable; null clears the NI number."),
    hasFixedAddress: zod
      .boolean()
      .describe("False requires address to be null."),
    address: zod
      .union([
        zod
          .object({
            addressLine1: zod.string(),
            addressLine2: zod.string().nullable(),
            addressLine3: zod.string().nullable(),
            addressLine4: zod.string().nullable(),
            townOrCity: zod.string().nullable(),
            postCode: zod.string().nullable(),
            county: zod.string().nullable(),
            country: zod
              .string()
              .min(
                updateApplicationDetailsBodyClientDetailsAddressOneCountryMin,
              )
              .max(
                updateApplicationDetailsBodyClientDetailsAddressOneCountryMax,
              ),
          })
          .nullable(),
        zod.null(),
      ])
      .describe(
        "Required but nullable; true hasFixedAddress requires an object.",
      ),
  }),
});

export type UpdateApplicationDetailsBody = zod.input<
  typeof UpdateApplicationDetailsBody
>;
export type UpdateApplicationDetailsBodyOutput = zod.output<
  typeof UpdateApplicationDetailsBody
>;
