/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const UpdateApplicationStatusRequestBody = zod.object({
  applicationState: zod.enum(["DRAFT", "COMPLETED"]),
});

export type UpdateApplicationStatusRequestBody = zod.input<
  typeof UpdateApplicationStatusRequestBody
>;
export type UpdateApplicationStatusRequestBodyOutput = zod.output<
  typeof UpdateApplicationStatusRequestBody
>;
