/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const updateApplicationDetailsHeadersIfMatchRegExp = new RegExp(
  '^"[0-9]+"$',
);

export const UpdateApplicationDetailsHeaders = zod.object({
  "If-Match": zod
    .string()
    .regex(updateApplicationDetailsHeadersIfMatchRegExp)
    .optional(),
});

export type UpdateApplicationDetailsHeaders = zod.input<
  typeof UpdateApplicationDetailsHeaders
>;
export type UpdateApplicationDetailsHeadersOutput = zod.output<
  typeof UpdateApplicationDetailsHeaders
>;
