/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const UpdateMeansDataRequestBody = zod.object({
  data: zod.looseObject({}),
  result: zod.looseObject({}),
});

export type UpdateMeansDataRequestBody = zod.input<
  typeof UpdateMeansDataRequestBody
>;
export type UpdateMeansDataRequestBodyOutput = zod.output<
  typeof UpdateMeansDataRequestBody
>;
