/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const UpdateApplicationMeansBody = zod.object({
  data: zod.looseObject({}),
  result: zod.looseObject({}),
});

export type UpdateApplicationMeansBody = zod.input<
  typeof UpdateApplicationMeansBody
>;
export type UpdateApplicationMeansBodyOutput = zod.output<
  typeof UpdateApplicationMeansBody
>;
