/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

export const updateAddressRequestBodyCountryMin = 2;
export const updateAddressRequestBodyCountryMax = 2;

export const UpdateAddressRequestBody = zod
  .object({
    addressLine1: zod.string(),
    addressLine2: zod.string().nullable(),
    addressLine3: zod.string().nullable(),
    addressLine4: zod.string().nullable(),
    townOrCity: zod.string().nullable(),
    postCode: zod.string().nullable(),
    county: zod.string().nullable(),
    country: zod
      .string()
      .min(updateAddressRequestBodyCountryMin)
      .max(updateAddressRequestBodyCountryMax),
  })
  .nullable();

export type UpdateAddressRequestBody = zod.input<
  typeof UpdateAddressRequestBody
>;
export type UpdateAddressRequestBodyOutput = zod.output<
  typeof UpdateAddressRequestBody
>;
