/**
 * Generated by Orval
 * Do not edit manually.
 * Provider Details API r1
 * OpenAPI spec version: v1.51.0
 */
import type { ProviderFirmOfficeListDto } from "../../model/providerFirmOfficeListDto.zod.gen.js";

import { fetcher } from "../../../../../lib/fetch.js";

export type getAllProviderOfficesResponse200 = {
  data: ProviderFirmOfficeListDto;
  status: 200;
};

export type getAllProviderOfficesResponse204 = {
  data: ProviderFirmOfficeListDto;
  status: 204;
};

export type getAllProviderOfficesResponse409 = {
  data: ProviderFirmOfficeListDto;
  status: 409;
};

export type getAllProviderOfficesResponse500 = {
  data: ProviderFirmOfficeListDto;
  status: 500;
};

export type getAllProviderOfficesResponseSuccess = (
  getAllProviderOfficesResponse200 | getAllProviderOfficesResponse204
) & {
  headers: Headers;
};
export type getAllProviderOfficesResponseError = (
  getAllProviderOfficesResponse409 | getAllProviderOfficesResponse500
) & {
  headers: Headers;
};

export type getAllProviderOfficesResponse =
  getAllProviderOfficesResponseSuccess | getAllProviderOfficesResponseError;

export const getGetAllProviderOfficesUrl = (firmId: number) => {
  return `/api/v1/provider-firms/${firmId}/provider-offices`;
};

/**
 *     Business Rules: - Firm is not end dated.                     - Firm is of type Legal Services Provider / Advocate / Chambers.                     - Firms of type Individual / QM Provider are NOT considered.                     - Firm Office is not end dated.                     - This DOES NOT check if a provider office has an active contract.
 * @summary Get all provider(firm) offices(sites) details based on a provider(firm) id.
 */
export const getAllProviderOffices = async (
  firmId: number,
  options?: RequestInit,
): Promise<getAllProviderOfficesResponse> => {
  return fetcher<getAllProviderOfficesResponse>(
    getGetAllProviderOfficesUrl(firmId),
    {
      ...options,
      method: "GET",
    },
  );
};
