/**
 * Error codes returned by Entra.
 *
 * These error codes will commonly be surfaced in an `AuthError` generated by
 * the MSAL library.
 */
export enum EntraErrorCode {
  // Custom auth error, which probably means SiLAS rejected auth rather than Entra.
  CUSTOM_AUTH_ERROR = "1003009",
}
