name: Setup Node and Dependencies
description: Setup Node.js, enable Corepack, and install dependencies

runs:
  using: "composite"
  steps:

    - name: Set up Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version-file: .nvmrc

    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Cache node_modules
      id: node-modules-cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

    - name: SLSA Supply Chain Security
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      uses: ministryofjustice/devsecops-actions/sca/slsa@7dc13c20e2bf541b8a77fa1320a04983b18846f6 # v1.6.0
      with:
        # TODO moment@2.31.0 published 15/09/2026, past the 72h minimum age gate on 18/09/2026 - remove after that
        # TODO proxy-addr@2.0.8 published 15/09/2026, past the 72h minimum age gate on 18/09/2026 - remove after that
        security-patch-package-exclusion: "moment,proxy-addr"

    - name: Install dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: yarn install --immutable
      shell: bash
