name: Setup Node and Dependencies
description: Setup Node.js, enable Corepack, and install dependencies

runs:
  using: "composite"
  steps:

    - name: Set up Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version-file: .nvmrc

    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Cache node_modules
      id: node-modules-cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

    - name: SLSA Supply Chain Security
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      uses: ministryofjustice/devsecops-actions/sca/slsa@4cd163be7859cd130800d6719d925318826038ea

    - name: Install dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: yarn install --immutable
      shell: bash
