# See documentation: https://yarnpkg.com/features/linkers#nodelinker-node-modules
nodeLinker: node-modules

# The minimum here would be 3d for patches, but given it can't be 
# configured for each semver level, we will apply it pragmatically
# to minor, which should be 7d.
#
# This setting will cause yarn to only resolve package releases that
# are more than 7 days old.
npmMinimalAgeGate: "7d"
