approvedGitRepositories:
  - "**"

# Allows logs from postinstall scripts to be displayed in the console during yarn install
enableInlineBuilds: true

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 7d
