approvedGitRepositories:
  - "**"

# Allows logs from postinstall scripts to be displayed in the console during yarn install
enableInlineBuilds: true

# Disables third party postinstall scripts from running during yarn install. 
# This is a security measure to prevent potentially malicious scripts.
enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 7d
