import type { OpenApiInfoObject, OutputOptions } from "@orval/core";

import "dotenv/config";
import { readFileSync } from "node:fs";
import { defineConfig } from "orval";

const API_SHA = readFileSync(".rcw-api-version", "utf-8").trim();

const sharedOutputConfig = (client: string): OutputOptions => ({
  clean: true,
  client: "fetch",
  fileExtension: ".gen.ts",
  formatter: "prettier",
  indexFiles: false,
  mock: {
    generators: [
      { path: `./tests/mocks/api/${client}/msw`, type: "msw" },
      { path: `./tests/mocks/api/${client}/fakers`, type: "faker" },
    ],
  },
  mode: "tags-split",
  override: {
    header: (info: OpenApiInfoObject) => [
      `Generated by Orval`,
      `Do not edit manually.`,
      ...(info.title ? [info.title] : []),
      ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
    ],
    mock: {
      nonNullable: true,
      required: true,
    },
    mutator: {
      extension: ".js",
      name: "fetcher",
      path: "./src/lib/fetch.ts",
    },
  },
  schemaFileExtension: ".zod.gen.ts",
  schemas: {
    path: `./src/api/clients/${client}/model`,
    type: "zod",
  },
  target: `./src/api/clients/${client}/schema`,
  tsconfig: "./tsconfig.json",
});

export default defineConfig({
  // TODO will be re-enabled in next pr
  // pda: {
  //   input: {
  //     filters: {
  //       mode: "include",
  //       schemas: ["ProviderFirmOfficeListDto"],
  //     },
  //     override: {
  //       transformer: (spec) => {
  //         const targetPath = "/api/v1/provider-firms/{firmId}/provider-offices";
  //         const pathItem = spec.paths?.[targetPath];
  //         return {
  //           ...spec,
  //           paths: pathItem ? { [targetPath]: pathItem } : {},
  //         };
  //       },
  //     },
  //     target: process.env.PDA_API_SPEC_URL ?? "",
  //   },
  //   output: sharedOutputConfig("pda"),
  // },
  rcw: {
    input: {
      filters: {
        mode: "exclude",
        tags: ["items"],
      },
      target: `https://raw.githubusercontent.com/ministryofjustice/laa-record-controlled-work-api/${API_SHA}/record-controlled-work-api/open-api-specification.yml`,
    },
    output: sharedOutputConfig("rcw"),
  },
});
