/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ClientDeclarationStatus = zod.enum(["DRAFT"]);

export type ClientDeclarationStatus = zod.input<typeof ClientDeclarationStatus>;
export type ClientDeclarationStatusOutput = zod.output<
  typeof ClientDeclarationStatus
>;
