/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const CreateApplicationRequestBody = zod.object({
  ecf: zod.string(),
  legalAidBefore: zod.string(),
  legalAidLast6Months: zod.string().optional(),
  reasonForYes: zod.string().optional(),
  firstName: zod.string(),
  lastName: zod.string(),
  dateOfBirth: zod.iso.date(),
  hasNINumber: zod.string(),
  niNumber: zod.string().optional(),
  haveAHomeAddress: zod.string(),
  addressLine1: zod.string(),
  addressLine2: zod.string().optional(),
  addressLine3: zod.string().optional(),
  addressLine4: zod.string().optional(),
  townOrCity: zod.string().optional(),
  county: zod.string().optional(),
  postcode: zod.string().optional(),
  country: zod.string(),
});

export type CreateApplicationRequestBody = zod.input<
  typeof CreateApplicationRequestBody
>;
export type CreateApplicationRequestBodyOutput = zod.output<
  typeof CreateApplicationRequestBody
>;
