/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const Declaration = zod.object({
  "id": zod.uuid().optional(),
  "clientDeclarationStatus": zod.enum(['DRAFT']).optional(),
  "declarationConfirmation": zod.boolean().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "createdBy": zod.string().optional(),
  "modifiedAt": zod.iso.datetime({"offset":true}).optional(),
  "modifiedBy": zod.string().optional()
})

export type Declaration = zod.input<typeof Declaration>;
export type DeclarationOutput = zod.output<typeof Declaration>;
