/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EvidenceStatus = zod.enum(["DRAFT"]);

export type EvidenceStatus = zod.input<typeof EvidenceStatus>;
export type EvidenceStatusOutput = zod.output<typeof EvidenceStatus>;
