/* eslint-disable @typescript-eslint/no-magic-numbers -- This is a cleaner way to define and destructure variables */

export const HTTP_STATUS = {
  BAD_GATEWAY: 502,
  BAD_REQUEST: 400,
  CREATED: 201,
  FORBIDDEN: 403,
  FOUND: 302,
  GATEWAY_TIMEOUT: 504,
  INTERNAL_SERVER_ERROR: 500,
  NOT_FOUND: 404,
  OK: 200,
  REQUEST_TIMEOUT: 408,
  SERVICE_UNAVAILABLE: 503,
  TOO_MANY_REQUESTS: 429,
  UNAUTHORIZED: 401,
} as const;

export const {
  BAD_GATEWAY,
  BAD_REQUEST,
  CREATED,
  FORBIDDEN,
  FOUND,
  GATEWAY_TIMEOUT,
  INTERNAL_SERVER_ERROR,
  NOT_FOUND,
  OK,
  REQUEST_TIMEOUT,
  SERVICE_UNAVAILABLE,
  TOO_MANY_REQUESTS,
  UNAUTHORIZED,
} = HTTP_STATUS;
