/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import config from "#/config.js";

import type { Application } from "../../model/application.zod.gen.js";

import type { Applications } from "../../model/applications.zod.gen.js";

import type { CreateApplicationRequestBody } from "../../model/createApplicationRequestBody.zod.gen.js";

import type { CreateApplicationResponseBody } from "../../model/createApplicationResponseBody.zod.gen.js";

export type getApplicationsResponse200 = {
  data: Applications;
  status: 200;
};

export type getApplicationsResponse400 = {
  data: void;
  status: 400;
};

export type getApplicationsResponse401 = {
  data: void;
  status: 401;
};

export type getApplicationsResponse403 = {
  data: void;
  status: 403;
};

export type getApplicationsResponse500 = {
  data: void;
  status: 500;
};

export type getApplicationsResponseSuccess = getApplicationsResponse200 & {
  headers: Headers;
};
export type getApplicationsResponseError = (
  | getApplicationsResponse400
  | getApplicationsResponse401
  | getApplicationsResponse403
  | getApplicationsResponse500
) & {
  headers: Headers;
};

export type getApplicationsResponse =
  getApplicationsResponseSuccess | getApplicationsResponseError;

export const getGetApplicationsUrl = () => {
  return `${config.api.rcw.baseUrl}/api/v1/applications`;
};

/**
 * @summary Get all applications
 */
export const getApplications = async (
  options?: RequestInit,
): Promise<getApplicationsResponse> => {
  const res = await fetch(getGetApplicationsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApplicationsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApplicationsResponse;
};

export type createApplicationResponse200 = {
  data: CreateApplicationResponseBody;
  status: 200;
};

export type createApplicationResponse400 = {
  data: void;
  status: 400;
};

export type createApplicationResponse401 = {
  data: void;
  status: 401;
};

export type createApplicationResponse403 = {
  data: void;
  status: 403;
};

export type createApplicationResponse404 = {
  data: void;
  status: 404;
};

export type createApplicationResponse500 = {
  data: void;
  status: 500;
};

export type createApplicationResponseSuccess = createApplicationResponse200 & {
  headers: Headers;
};
export type createApplicationResponseError = (
  | createApplicationResponse400
  | createApplicationResponse401
  | createApplicationResponse403
  | createApplicationResponse404
  | createApplicationResponse500
) & {
  headers: Headers;
};

export type createApplicationResponse =
  createApplicationResponseSuccess | createApplicationResponseError;

export const getCreateApplicationUrl = () => {
  return `${config.api.rcw.baseUrl}/api/v1/applications`;
};

/**
 * @summary Create an application
 */
export const createApplication = async (
  createApplicationRequestBody?: CreateApplicationRequestBody,
  options?: RequestInit,
): Promise<createApplicationResponse> => {
  const res = await fetch(getCreateApplicationUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createApplicationRequestBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createApplicationResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createApplicationResponse;
};

export type getApplicationResponse200 = {
  data: Application;
  status: 200;
};

export type getApplicationResponse401 = {
  data: void;
  status: 401;
};

export type getApplicationResponse403 = {
  data: void;
  status: 403;
};

export type getApplicationResponse404 = {
  data: void;
  status: 404;
};

export type getApplicationResponse500 = {
  data: void;
  status: 500;
};

export type getApplicationResponseSuccess = getApplicationResponse200 & {
  headers: Headers;
};
export type getApplicationResponseError = (
  | getApplicationResponse401
  | getApplicationResponse403
  | getApplicationResponse404
  | getApplicationResponse500
) & {
  headers: Headers;
};

export type getApplicationResponse =
  getApplicationResponseSuccess | getApplicationResponseError;

export const getGetApplicationUrl = (id: string) => {
  return `${config.api.rcw.baseUrl}/api/v1/applications/${id}`;
};

/**
 * @summary Get application by ID
 */
export const getApplication = async (
  id: string,
  options?: RequestInit,
): Promise<getApplicationResponse> => {
  const res = await fetch(getGetApplicationUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApplicationResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApplicationResponse;
};
