/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import config from "#/config.js";

import type { Application } from "../../model/application.zod.gen.js";

import type { Applications } from "../../model/applications.zod.gen.js";

import type { CreateApplicationRequestBody } from "../../model/createApplicationRequestBody.zod.gen.js";

import type { GetApplicationsParams } from "../../model/getApplicationsParams.zod.gen.js";

import type { UpdateMeansDataRequestBody } from "../../model/updateMeansDataRequestBody.zod.gen.js";

export type getApplicationsResponse200 = {
  data: Applications;
  status: 200;
};

export type getApplicationsResponse400 = {
  data: void;
  status: 400;
};

export type getApplicationsResponse401 = {
  data: void;
  status: 401;
};

export type getApplicationsResponse403 = {
  data: void;
  status: 403;
};

export type getApplicationsResponse500 = {
  data: void;
  status: 500;
};

export type getApplicationsResponseSuccess = getApplicationsResponse200 & {
  headers: Headers;
};
export type getApplicationsResponseError = (
  | getApplicationsResponse400
  | getApplicationsResponse401
  | getApplicationsResponse403
  | getApplicationsResponse500
) & {
  headers: Headers;
};

export type getApplicationsResponse =
  getApplicationsResponseSuccess | getApplicationsResponseError;

export const getGetApplicationsUrl = (params?: GetApplicationsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `${config.api.rcw.baseUrl}/api/v1/applications?${stringifiedParams}`
    : `${config.api.rcw.baseUrl}/api/v1/applications`;
};

/**
 * @summary Get all applications
 */
export const getApplications = async (
  params?: GetApplicationsParams,
  options?: RequestInit,
): Promise<getApplicationsResponse> => {
  const res = await fetch(getGetApplicationsUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApplicationsResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApplicationsResponse;
};

export type createApplicationResponse201 = {
  data: void;
  status: 201;
};

export type createApplicationResponse400 = {
  data: void;
  status: 400;
};

export type createApplicationResponse401 = {
  data: void;
  status: 401;
};

export type createApplicationResponse403 = {
  data: void;
  status: 403;
};

export type createApplicationResponse404 = {
  data: void;
  status: 404;
};

export type createApplicationResponse500 = {
  data: void;
  status: 500;
};

export type createApplicationResponseSuccess = createApplicationResponse201 & {
  headers: Headers;
};
export type createApplicationResponseError = (
  | createApplicationResponse400
  | createApplicationResponse401
  | createApplicationResponse403
  | createApplicationResponse404
  | createApplicationResponse500
) & {
  headers: Headers;
};

export type createApplicationResponse =
  createApplicationResponseSuccess | createApplicationResponseError;

export const getCreateApplicationUrl = () => {
  return `${config.api.rcw.baseUrl}/api/v1/applications`;
};

/**
 * @summary Create an application
 */
export const createApplication = async (
  createApplicationRequestBody?: CreateApplicationRequestBody,
  options?: RequestInit,
): Promise<createApplicationResponse> => {
  const res = await fetch(getCreateApplicationUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createApplicationRequestBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createApplicationResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createApplicationResponse;
};

export type getApplicationResponse200 = {
  data: Application;
  status: 200;
};

export type getApplicationResponse401 = {
  data: void;
  status: 401;
};

export type getApplicationResponse403 = {
  data: void;
  status: 403;
};

export type getApplicationResponse404 = {
  data: void;
  status: 404;
};

export type getApplicationResponse500 = {
  data: void;
  status: 500;
};

export type getApplicationResponseSuccess = getApplicationResponse200 & {
  headers: Headers;
};
export type getApplicationResponseError = (
  | getApplicationResponse401
  | getApplicationResponse403
  | getApplicationResponse404
  | getApplicationResponse500
) & {
  headers: Headers;
};

export type getApplicationResponse =
  getApplicationResponseSuccess | getApplicationResponseError;

export const getGetApplicationUrl = (id: string) => {
  return `${config.api.rcw.baseUrl}/api/v1/applications/${id}`;
};

/**
 * @summary Get application by ID
 */
export const getApplication = async (
  id: string,
  options?: RequestInit,
): Promise<getApplicationResponse> => {
  const res = await fetch(getGetApplicationUrl(id), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApplicationResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getApplicationResponse;
};

export type updateApplicationMeansResponse204 = {
  data: void;
  status: 204;
};

export type updateApplicationMeansResponse400 = {
  data: void;
  status: 400;
};

export type updateApplicationMeansResponse401 = {
  data: void;
  status: 401;
};

export type updateApplicationMeansResponse403 = {
  data: void;
  status: 403;
};

export type updateApplicationMeansResponse404 = {
  data: void;
  status: 404;
};

export type updateApplicationMeansResponse409 = {
  data: void;
  status: 409;
};

export type updateApplicationMeansResponse500 = {
  data: void;
  status: 500;
};

export type updateApplicationMeansResponseSuccess =
  updateApplicationMeansResponse204 & {
    headers: Headers;
  };
export type updateApplicationMeansResponseError = (
  | updateApplicationMeansResponse400
  | updateApplicationMeansResponse401
  | updateApplicationMeansResponse403
  | updateApplicationMeansResponse404
  | updateApplicationMeansResponse409
  | updateApplicationMeansResponse500
) & {
  headers: Headers;
};

export type updateApplicationMeansResponse =
  updateApplicationMeansResponseSuccess | updateApplicationMeansResponseError;

export const getUpdateApplicationMeansUrl = (id: string) => {
  return `${config.api.rcw.baseUrl}/api/v1/applications/${id}/means`;
};

/**
 * @summary Update the means data for an application
 */
export const updateApplicationMeans = async (
  id: string,
  updateMeansDataRequestBody: UpdateMeansDataRequestBody,
  options?: RequestInit,
): Promise<updateApplicationMeansResponse> => {
  const res = await fetch(getUpdateApplicationMeansUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateMeansDataRequestBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateApplicationMeansResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateApplicationMeansResponse;
};
