name: Build and Push Image
description: Build Image and Push to a Container Registry (with caching)

inputs:
  image_registry:
    required: true
    description: "Image Registry URL"
  image_repo:
    required: true
    description: "Image Repository URL"
  dockerfile_path:
    required: true
    description: "Dockerfile Path"
    default: "Dockerfile"
  image_tag:
    required: true
    description: "Image Tag"
    default: ${{ github.sha }}

outputs:
  image_registry:
    description: "Image Registry URL"
    value: ${{ steps.output.outputs.image_registry }}
  image_repo:
    description: "Image Repo Path"
    value: ${{ steps.output.outputs.image_repo }}
  image_tag:
    description: "Image Tag"
    value: ${{ steps.output.outputs.image_tag }}
  image_uri:
    description: "Image URI"
    value: ${{ steps.output.outputs.image_uri }}

runs:
  using: "composite"
  steps:
    - name: Docker Build, Push and Export with Cache
      id: build_and_push
      run: |
        image_uri=${{ inputs.image_registry }}/${{ inputs.image_repo }}:${{ inputs.image_tag }}
        runner_image=rcw-runner:${{ inputs.image_tag }}

        docker buildx build \
          --load \
          --cache-from=type=local,src=/tmp/.buildx-cache \
          --cache-to=type=local,dest=/tmp/.buildx-cache-new \
          -t "$image_uri" \
          -f ${{ inputs.dockerfile_path }} .

        docker push "$image_uri"
        docker tag "$image_uri" "$runner_image"
        docker save "$runner_image" -o rcw-runner-image.tar

        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      shell: bash

    - name: Upload runner image
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: rcw-runner-image
        path: rcw-runner-image.tar
        retention-days: 1

    - name: Output
      id: output
      run: |
        echo image_registry=${{ inputs.image_registry }} >> "$GITHUB_OUTPUT"
        echo image_repo=${{ inputs.image_repo }} >> "$GITHUB_OUTPUT"
        echo image_tag=${{ inputs.image_tag }} >> "$GITHUB_OUTPUT"
        echo image_uri="${{ inputs.image_registry }}/${{ inputs.image_repo }}:${{ inputs.image_tag }}" >> "$GITHUB_OUTPUT"
      shell: bash
