/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { Application } from "../../../../../../src/api/clients/rcw/model/application.zod.gen.js";

import { ApplicationStatus } from "../../../../../../src/api/clients/rcw/model/applicationStatus.zod.gen.js";

import type { Applications } from "../../../../../../src/api/clients/rcw/model/applications.zod.gen.js";

import { ClientDeclarationStatus } from "../../../../../../src/api/clients/rcw/model/clientDeclarationStatus.zod.gen.js";

import type { CreateApplicationResponseBody } from "../../../../../../src/api/clients/rcw/model/createApplicationResponseBody.zod.gen.js";

import { EvidenceStatus } from "../../../../../../src/api/clients/rcw/model/evidenceStatus.zod.gen.js";

export const getGetApplicationsResponseMock = (): Applications =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.string.uuid(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    applicationRefNumber: faker.string.alpha({ length: { min: 10, max: 20 } }),
    modifiedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  }));

export const getCreateApplicationResponseMock = (
  overrideResponse: Partial<
    Extract<CreateApplicationResponseBody, object>
  > = {},
): CreateApplicationResponseBody => ({
  id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
  ecf: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  legalAidBefore: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  legalAidLast6Months: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  reasonForYes: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  firstName: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  lastName: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  dateOfBirth: faker.helpers.arrayElement([
    faker.date.past().toISOString().slice(0, 10),
    undefined,
  ]),
  hasNINumber: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  niNumber: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  haveAHomeAddress: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  addressLine1: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  addressLine2: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  addressLine3: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  addressLine4: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  townOrCity: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  county: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  postcode: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  country: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetApplicationResponseMock = (
  overrideResponse: Partial<Extract<Application, object>> = {},
): Application => ({
  id: faker.string.uuid(),
  individualLegalAidNumber: faker.string.uuid(),
  providerFirmId: faker.string.uuid(),
  providerOfficeId: faker.string.uuid(),
  meansAssessmentId: faker.helpers.arrayElement([
    faker.string.uuid(),
    undefined,
  ]),
  clientDetails: {
    id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
    firstName: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    lastName: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    dateOfBirth: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 10),
      undefined,
    ]),
    niNumber: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    hasFixedAddress: faker.helpers.arrayElement([
      faker.datatype.boolean(),
      undefined,
    ]),
    address: faker.helpers.arrayElement([
      {
        id: faker.string.uuid(),
        addressLine1: faker.string.alpha({ length: { min: 10, max: 20 } }),
        addressLine2: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        addressLine3: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        addressLine4: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        townOrCity: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        postCode: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        county: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          undefined,
        ]),
        country: faker.string.alpha({ length: { min: 10, max: 20 } }),
        createdAt: faker.helpers.arrayElement([
          faker.date.past().toISOString().slice(0, 19) + "Z",
          undefined,
        ]),
        modifiedAt: faker.helpers.arrayElement([
          faker.date.past().toISOString().slice(0, 19) + "Z",
          undefined,
        ]),
      },
      undefined,
    ]),
    createdAt: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + "Z",
      undefined,
    ]),
    modifiedAt: faker.helpers.arrayElement([
      faker.date.past().toISOString().slice(0, 19) + "Z",
      undefined,
    ]),
  },
  applicationStatus: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(ApplicationStatus)),
    undefined,
  ]),
  declaration: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      clientDeclarationStatus: faker.helpers.arrayElement([
        faker.helpers.arrayElement(Object.values(ClientDeclarationStatus)),
        undefined,
      ]),
      declarationConfirmation: faker.helpers.arrayElement([
        faker.datatype.boolean(),
        undefined,
      ]),
      createdAt: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        undefined,
      ]),
      createdBy: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      modifiedAt: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        undefined,
      ]),
      modifiedBy: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
    },
    undefined,
  ]),
  evidence: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      evidenceStatus: faker.helpers.arrayElement([
        faker.helpers.arrayElement(Object.values(EvidenceStatus)),
        undefined,
      ]),
      payeIncomeEvidence: faker.helpers.arrayElement([
        faker.datatype.boolean(),
        undefined,
      ]),
      otherIncomeEvidence: faker.helpers.arrayElement([
        faker.datatype.boolean(),
        undefined,
      ]),
      housingCostsEvidence: faker.helpers.arrayElement([
        faker.datatype.boolean(),
        undefined,
      ]),
      capitalEvidence: faker.helpers.arrayElement([
        faker.datatype.boolean(),
        undefined,
      ]),
      createdAt: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        undefined,
      ]),
      createdBy: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      modifiedAt: faker.helpers.arrayElement([
        faker.date.past().toISOString().slice(0, 19) + "Z",
        undefined,
      ]),
      modifiedBy: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
    },
    undefined,
  ]),
  reasonForReapplication: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  meansAssessmentRequired: faker.helpers.arrayElement([
    faker.datatype.boolean(),
    undefined,
  ]),
  typeOfNonMeans: faker.helpers.arrayElement([
    faker.datatype.boolean(),
    undefined,
  ]),
  ecfFlag: faker.datatype.boolean(),
  contribution: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  applicationType: faker.string.alpha({ length: { min: 10, max: 20 } }),
  createdAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  createdBy: faker.string.alpha({ length: { min: 10, max: 20 } }),
  modifiedAt: faker.date.past().toISOString().slice(0, 19) + "Z",
  modifiedBy: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getGetApplicationsMockHandler = (
  overrideResponse?:
    | Applications
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Applications> | Applications),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/v1/applications",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetApplicationsResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getCreateApplicationMockHandler = (
  overrideResponse?:
    | CreateApplicationResponseBody
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) =>
        Promise<CreateApplicationResponseBody> | CreateApplicationResponseBody),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/v1/applications",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getCreateApplicationResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetApplicationMockHandler = (
  overrideResponse?:
    | Application
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Application> | Application),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/v1/applications/:id",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetApplicationResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getApplicationsMock = () => [
  getGetApplicationsMockHandler(),
  getCreateApplicationMockHandler(),
  getGetApplicationMockHandler(),
];
