/**
 * Generated by Orval
 * Do not edit manually.
 * Record Controlled Work API
 * OpenAPI spec version: 1.0.0
 */
import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { Application } from "../../../../../../src/api/clients/rcw/model/application.zod.gen.js";

import type { Applications } from "../../../../../../src/api/clients/rcw/model/applications.zod.gen.js";

import type { CreateApplicationResponseBody } from "../../../../../../src/api/clients/rcw/model/createApplicationResponseBody.zod.gen.js";

import {
  getCreateApplicationResponseMock,
  getGetApplicationResponseMock,
  getGetApplicationsResponseMock,
} from "../../fakers/applications/applications.faker.gen.gen.js";

export {
  getGetApplicationsResponseMock,
  getCreateApplicationResponseMock,
  getGetApplicationResponseMock,
} from "../../fakers/applications/applications.faker.gen.gen.js";

export type KeysWithNull<O> = {
  [K in keyof O]-?: null extends O[K] ? K : never;
}[keyof O];

export type MockWithNullableOverrides<
  T,
  O extends Partial<T>,
  M extends Record<keyof T, unknown>,
> = Omit<M, Extract<KeysWithNull<O>, keyof T>> & {
  [K in Extract<KeysWithNull<O>, keyof T>]: M[K] | null;
};

export type ApplicationsMock = Applications;

export type CreateApplicationResponseBodyMock = {
  [
    K in keyof Required<NonNullable<CreateApplicationResponseBody>>
  ]: NonNullable<Required<NonNullable<CreateApplicationResponseBody>>[K]>;
};

export type ApplicationMock = {
  [K in keyof Required<NonNullable<Application>>]: NonNullable<
    Required<NonNullable<Application>>[K]
  >;
};

export const getGetApplicationsMockHandler = (
  overrideResponse?:
    | Applications
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Applications> | Applications),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/v1/applications",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetApplicationsResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getCreateApplicationMockHandler = (
  overrideResponse?:
    | CreateApplicationResponseBody
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) =>
        Promise<CreateApplicationResponseBody> | CreateApplicationResponseBody),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/v1/applications",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getCreateApplicationResponseMock(),
        { status: 201 },
      );
    },
    options,
  );
};

export const getGetApplicationMockHandler = (
  overrideResponse?:
    | Application
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Application> | Application),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/v1/applications/:id",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetApplicationResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getApplicationsMock = () => [
  getGetApplicationsMockHandler(),
  getCreateApplicationMockHandler(),
  getGetApplicationMockHandler(),
];
