/**
 * Generated by Orval
 * Do not edit manually.
 * Provider Details API r1
 * OpenAPI spec version: v1.51.1
 */
import { z as zod } from "zod";

export const ProviderFirmOfficeListDto = zod.object({
  firm: zod
    .object({
      firmNumber: zod.string().nullish(),
      firmId: zod.number().nullish(),
      ccmsFirmId: zod.number().nullish(),
      parentFirmId: zod.number().nullish(),
      firmName: zod.string().nullish(),
      firmType: zod.string().nullish(),
      constitutionalStatus: zod.string().nullish(),
      solicitorAdvocateYN: zod.string().nullish(),
      advocateLevel: zod.string().nullish(),
      barCouncilRoll: zod.string().nullish(),
      companyHouseNumber: zod.string().nullish(),
    })
    .optional(),
  offices: zod
    .array(
      zod.object({
        firmOfficeId: zod.number().nullish(),
        ccmsFirmOfficeId: zod.number().nullish(),
        firmOfficeCode: zod.string().nullish(),
        officeName: zod.string().nullish(),
        officeCodeAlt: zod.string().nullish(),
        type: zod.string().nullish(),
        addressLine1: zod.string().nullish(),
        addressLine2: zod.string().nullish(),
        addressLine3: zod.string().nullish(),
        addressLine4: zod.string().nullish(),
        city: zod.string().nullish(),
        county: zod.string().nullish(),
        postCode: zod.string().nullish(),
        dxCentre: zod.string().nullish(),
        dxNumber: zod.string().nullish(),
        telephoneAreaCode: zod.string().nullish(),
        telephoneNumber: zod.string().nullish(),
        faxAreaCode: zod.string().nullish(),
        faxNumber: zod.string().nullish(),
        emailAddress: zod.string().nullish(),
        vatRegistrationNumber: zod.string().nullish(),
        headOffice: zod.string().nullish(),
        creationDate: zod.iso.date().nullish(),
        lscRegion: zod.string().nullish(),
        lscBidZone: zod.string().nullish(),
        lscAreaOffice: zod.string().nullish(),
        cjsForceName: zod.string().nullish(),
        localAuthority: zod.string().nullish(),
        policeStationAreaName: zod.string().nullish(),
        dutySolicitorAreaName: zod.string().nullish(),
      }),
    )
    .optional(),
});

export type ProviderFirmOfficeListDto = zod.input<
  typeof ProviderFirmOfficeListDto
>;
export type ProviderFirmOfficeListDtoOutput = zod.output<
  typeof ProviderFirmOfficeListDto
>;
