apiVersion: v1
kind: Service
metadata:
  name: {{ include "laa-record-controlled-work.fullname" . }}-rcw
  labels:
    {{- include "laa-record-controlled-work.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "laa-record-controlled-work.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rcw