import type { OpenApiInfoObject, OutputOptions } from "@orval/core";

/**
 * Shared output configuration used by all Orval client generators.
 * @param client The API client name
 * @param runtimeBaseUrl The runtime base URL configuration path
 * @returns The configured output options for Orval
 */
export function sharedOutputConfig(
  client: string,
  runtimeBaseUrl: string,
): OutputOptions {
  return {
    baseUrl: {
      imports: [
        {
          default: true,
          importPath: "#/config.js",
          name: "config",
        },
      ],
      runtime: runtimeBaseUrl,
    },
    clean: true,
    client: "fetch",
    fileExtension: ".gen.ts",
    formatter: "prettier",
    indexFiles: false,
    mock: {
      generators: [
        { path: `./tests/mocks/api/${client}/msw`, type: "msw" },
        {
          path: `./tests/mocks/api/${client}/fakers`,
          type: "faker",
        },
      ],
    },
    mode: "tags-split",
    override: {
      header: (info: OpenApiInfoObject) => [
        `Generated by Orval`,
        `Do not edit manually.`,
        ...(info.title ? [info.title] : []),
        ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
      ],
      mock: {
        nonNullable: true,
        required: true,
      },
    },
    schemaFileExtension: ".zod.gen.ts",
    schemas: {
      path: `./src/api/clients/${client}/model`,
      type: "zod",
    },
    target: `./src/api/clients/${client}/schema`,
    tsconfig: "./tsconfig.json",
  };
}
