/**
 * Generated by Orval
 * Do not edit manually.
 * Provider Details API r1
 * OpenAPI spec version: v1.51.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { ProviderFirmOfficeListDto } from "../../../../../../src/api/clients/pda/model/providerFirmOfficeListDto.zod.gen.js";

export const getGetAllProviderOfficesResponseMock = (
  overrideResponse: Partial<Extract<ProviderFirmOfficeListDto, object>> = {},
): ProviderFirmOfficeListDto =>
  faker.helpers.arrayElement([
    {
      firm: faker.helpers.arrayElement([null, undefined]),
      offices: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => null),
        undefined,
      ]),
      ...overrideResponse,
    },
    {
      firm: faker.helpers.arrayElement([null, undefined]),
      offices: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => null),
        undefined,
      ]),
      ...overrideResponse,
    },
  ]);

export const getGetAllProviderOfficesMockHandler = (
  overrideResponse?:
    | ProviderFirmOfficeListDto
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ProviderFirmOfficeListDto> | ProviderFirmOfficeListDto),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/v1/provider-firms/:firmId/provider-offices",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetAllProviderOfficesResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getProviderFirmsEndpointsMock = () => [
  getGetAllProviderOfficesMockHandler(),
];
