/**
 * Generated by Orval
 * Do not edit manually.
 * Provider Details API r1
 * OpenAPI spec version: v1.51.0
 */
import { faker } from "@faker-js/faker";

import type { ProviderFirmOfficeListDto } from "../../../../../../src/api/clients/pda/model/providerFirmOfficeListDto.zod.gen.js";

export const getGetAllProviderOfficesResponseMock = (
  overrideResponse: Partial<Extract<ProviderFirmOfficeListDto, object>> = {},
): ProviderFirmOfficeListDto =>
  faker.helpers.arrayElement([
    {
      firm: faker.helpers.arrayElement([null, undefined]),
      offices: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => null),
        undefined,
      ]),
      ...overrideResponse,
    },
    {
      firm: faker.helpers.arrayElement([null, undefined]),
      offices: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => null),
        undefined,
      ]),
      ...overrideResponse,
    },
  ]);
