/**
 * Generated by Orval
 * Do not edit manually.
 * Provider Details API r1
 * OpenAPI spec version: v1.51.1
 */
import { faker } from "@faker-js/faker";

import type { ProviderFirmOfficeListDto } from "../../../../../../src/api/clients/pda/model/providerFirmOfficeListDto.zod.gen.js";

export type KeysWithNull<O> = {
  [K in keyof O]-?: null extends O[K] ? K : never;
}[keyof O];

export type MockWithNullableOverrides<
  T,
  O extends Partial<T>,
  M extends Record<keyof T, unknown>,
> = Omit<M, Extract<KeysWithNull<O>, keyof T>> & {
  [K in Extract<KeysWithNull<O>, keyof T>]: M[K] | null;
};

export type ProviderFirmOfficeListDtoMock = {
  [K in keyof Required<NonNullable<ProviderFirmOfficeListDto>>]: NonNullable<
    Required<NonNullable<ProviderFirmOfficeListDto>>[K]
  >;
};

export const getGetAllProviderOfficesResponseMock = <
  O extends Partial<Extract<ProviderFirmOfficeListDto, object>> = {},
>(
  overrideResponse?: O,
): MockWithNullableOverrides<
  ProviderFirmOfficeListDto,
  O,
  ProviderFirmOfficeListDtoMock
> =>
  faker.helpers.arrayElement([
    {
      firm: null,
      offices: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => null),
      ...overrideResponse,
    },
    {
      firm: null,
      offices: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => null),
      ...overrideResponse,
    },
  ]) as MockWithNullableOverrides<
    ProviderFirmOfficeListDto,
    O,
    ProviderFirmOfficeListDtoMock
  >;
