serviceAccount:
  name: "your-github-action-service-account"

ingress:
  hosts:
    - host: your-production-namespace.cloud-platform.service.justice.gov.uk
      paths:
        - path: /
          pathType: Prefix
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "ingress-name-laa-record-controlled-work-laa-record-controlled-work-production-green"

rcw:
  replicaCount: 2

  env:
    NODE_ENV: "production"

ccq:
  replicaCount: 2

  env:
    HOST_CLIENT_URL: https://laa-record-controlled-work-prod.cloud-platform.service.justice.gov.uk