serviceAccount:
  name: "your-github-action-service-account"

ingress:
  hosts:
    - host: your-production-namespace.cloud-platform.service.justice.gov.uk
      paths:
        - path: /
          pathType: Prefix
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "ingress-name-laa-record-controlled-work-laa-record-controlled-work-production-green"

rcw:
  replicaCount: 2

  env:
    NODE_ENV: "production"

nginx:
  replicaCount: 1

  image:
    # Overridden at deploy time to ECR; see deploy.sh and docker-images.env
    repository: nginxinc/nginx-unprivileged
    pullPolicy: Always
    tag: alpine

  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 32Mi
