serviceAccount:
  name: "rcw-github-action-service-account"

ingress:
  hosts:
    - host: record-controlled-work-uat.cloud-platform.service.justice.gov.uk
      paths:
        - path: /
          pathType: Prefix
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "laa-record-controlled-work-record-controlled-work-uat-green"

rcw:
  replicaCount: 1

  env:
    NODE_ENV: "uat"

nginx:
  replicaCount: 1

  image:
    # Overridden at deploy time to ECR; see deploy.sh and docker-images.env
    repository: nginxinc/nginx-unprivileged
    pullPolicy: Always
    tag: alpine

  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 32Mi
