serviceAccount:
  name: rcw-github-action-service-account

ingress:
  hosts:
    - host: laa-record-controlled-work-uat.cloud-platform.service.justice.gov.uk
      paths:
        - path: /
          pathType: Prefix
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: laa-record-controlled-work-laa-record-controlled-work-uat-green

rcw:
  replicaCount: 1

  env:
    NODE_ENV: uat
    ENTRA_REDIRECT_URI: https://laa-record-controlled-work-uat.cloud-platform.service.justice.gov.uk/auth/code/callback
    API_BASE_URL: http://laa-record-controlled-work-api.laa-record-controlled-work-api-uat.svc:8081

ccq:
  replicaCount: 1

  env:
    HOST_SERVICE_URL: https://laa-record-controlled-work-uat.cloud-platform.service.justice.gov.uk
