export enum AnswerKey {
  ukAddressLine1 = "ukAddressLine1",
  ukAddressLine2 = "ukAddressLine2",
  osAddressLine1 = "osAddressLine1",
  osAddressLine2 = "osAddressLine2",
  osAddressLine3 = "osAddressLine3",
  osAddressLine4 = "osAddressLine4",
  osCountry = "osCountry",
  ukCountry = "ukCountry",
  ukCounty = "ukCounty",
  dateOfBirth = "dateOfBirth",
  ecf = "ecf",
  firstName = "firstName",
  hasNINumber = "hasNINumber",
  haveAHomeAddress = "haveAHomeAddress",
  lastName = "lastName",
  legalAidBefore = "legalAidBefore",
  legalAidLast6Months = "legalAidLast6Months",
  niNumber = "niNumber",
  ukPostcode = "ukPostcode",
  reasonForYes = "reasonForYes",
  ukTownOrCity = "ukTownOrCity",
}
