name: CICD

on:
  push:
    branches:
      - "**"
  workflow_dispatch: # Allows manual triggering of the workflow
  workflow_call:
    inputs:
      sha:
        description: "The commit SHA to deploy"
        type: string
        default: ''
      branch-ref:
        description: "The branch ref to deploy as ephemeral environment"
        type: string
        default: ''

jobs:
  code-linting:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Setup Node and Dependencies
        uses: ./.github/actions/setup-node

      - name: Run ESLint
        run: yarn lint

  code-security-audit:
    name: Code Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Setup Node and Dependencies
        uses: ./.github/actions/setup-node

      - name: Run security audit
        run: yarn npm audit

  snyk:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Build local Docker image
        working-directory: ${{ github.workspace }}
        run: |
          docker build -t laa-record-controlled-work ./
          docker save laa-record-controlled-work -o image.tar

      - name: Run Snyk to scan Docker image from tarball
        uses: snyk/actions/docker@9adf32b1121593767fc3c057af55b55db032dc04 # master
        with:
          image: image.tar
          args: --docker --severity-threshold=high --policy-path=.snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  snyk-infra:
    name: Snyk Infra Scan
    uses: ./.github/workflows/snyk-infra.yml
    secrets: inherit

  mocha-unit-tests:
    name: Mocha Unit Tests
    uses: ./.github/workflows/mocha.yml
    with:
      sha: ${{ inputs.sha || github.sha }}

  playwright:
    name: Playwright Tests
    uses: ./.github/workflows/playwright.yml
    with:
      sha: ${{ inputs.sha || github.sha }}

  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Set up AWS credentials for ECR and Kubernetes
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}

      - uses: aws-actions/amazon-ecr-login@f2e9fc6c2b355c1890b65e6f6f0e2ac3e6e22f78
        id: login-ecr

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@21162887f0d6e25b4e8eafb0cf44cf9bf7f6acd3

      - name: Cache Docker layers
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ inputs.sha || github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push image with local action
        uses: ./.github/actions/build_and_push
        with:
          image_registry: ${{ secrets.ECR_REGISTRY_URL }}
          image_repo: ${{ vars.ECR_REPOSITORY }}
          dockerfile_path: Dockerfile
          image_tag: ${{ inputs.sha || github.sha }}

  deploy-uat:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      inputs.branch-ref != '' ||
      (github.ref_name == 'main' && !startsWith(github.ref, 'refs/heads/gh-readonly-queue/'))
    uses: ./.github/workflows/deploy-environment.yml
    with:
      app-environment: uat
      sha: ${{ inputs.sha || github.sha }}
      branch-ref: ${{ inputs.branch-ref }}
    concurrency:
      group: deploy-uat-${{ github.ref }}
      cancel-in-progress: false
    needs:
      - code-linting
      - code-security-audit
      - snyk
      - build-image
      - mocha-unit-tests
      - playwright
      - snyk-infra
    secrets: inherit

  # deploy-staging:
  #   if: github.ref == 'refs/heads/main'
  #   concurrency:
  #     group: deploy-staging-${{ github.ref }}
  #     cancel-in-progress: false
  #   needs:
  #     - deploy-uat
  #   uses: ./.github/workflows/deploy-environment.yml
  #   with:
  #     app-environment: staging
  #   secrets: inherit

  # deploy-production:
  #   if: github.ref == 'refs/heads/main'
  #   concurrency:
  #     group: deploy-production-${{ github.ref }}
  #     cancel-in-progress: false
  #   needs:
  #     - deploy-staging
  #   uses: ./.github/workflows/deploy-environment.yml
  #   with:
  #     app-environment: production
  #   secrets: inherit
