name: Cleanup Ephemeral Release

on:
  pull_request:
    types:
      - closed
jobs:
  cleanup_ephemeral_release:
    runs-on: ubuntu-latest
    environment: uat
    # Update this to true if there is a DB and you have PVCs
    env:
      DELETE_ALL_PVC: false
    outputs:
      branch-name: ${{ steps.extract_branch.outputs.branch }}
      release-name: ${{ steps.extract_release.outputs.release }}
      delete-message: ${{ steps.delete_release.outputs.message }}

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Extract branch name
        id: extract_branch
        shell: bash
        env:
          BRANCH_NAME: ${{ github.head_ref || 'not_given' }}
        run: |
          if [ "$BRANCH_NAME" == "not_given" ]; then
            branch="${GITHUB_HEAD_REF:-${GITHUB_REF##*/}}"
          else
            branch="$BRANCH_NAME"
          fi
          echo "branch=$branch" >> $GITHUB_OUTPUT

      - name: Extract release name
        id: extract_release
        shell: bash
        env:
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
        run: |
          echo "release=$(./scripts/release-name.sh "$BRANCH")" >> $GITHUB_OUTPUT

      - name: Authenticate to the cluster
        id: authenticate_to_cluster
        uses: ministryofjustice/laa-reusable-github-actions/.github/actions/authenticate_to_cluster@e0b6695b8ec0679ae36920155fd06539c685a096
        with:
          kube-cert: ${{ secrets.KUBE_CERT }}
          kube-token: ${{ secrets.KUBE_TOKEN }}
          kube-cluster: ${{ secrets.KUBE_CLUSTER }}
          kube-namespace: ${{ secrets.KUBE_NAMESPACE }}

      - name: Delete ephemeral release
        id: delete_release
        shell: bash
        run: |
          release_name=${{ steps.extract_release.outputs.release }}
          found=$(helm list --filter "$release_name" | grep "$release_name" || [[ $? == 1 ]])

          if [[ ! -z "$found" ]]
          then
            helm uninstall $release_name

            if [[ "${DELETE_ALL_PVC}" = "true" ]]
            then
              kubectl delete pvc -l app.kubernetes.io/instance=$release_name
            fi

            echo "message=\"Deleted UAT ephemeral release ${release_name}\"" >> $GITHUB_OUTPUT
          else
            echo "message=\"UAT ephemeral release, ${release_name}, not found\"" >> $GITHUB_OUTPUT
          fi

      - name: Output result
        shell: bash
        run: echo ${{ steps.delete_release.outputs.message  }}\
