name: Deploy to Environment

on:
  workflow_call:
    inputs:
      app-environment:
        required: true
        type: string
      sha:
        description: "Commit SHA to deploy"
        type: string
        required: true
      branch-ref:
        description: "Branch ref for ephemeral deployments"
        type: string
        default: ''

jobs:
  deploy:
    name: Deploy to ${{ inputs.app-environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.app-environment }}
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          sha: ${{ inputs.sha }}
          branch-ref: ${{ inputs.branch-ref }}
          app-environment: ${{ inputs.app-environment }}
          ecr-registry_url: ${{ secrets.ECR_REGISTRY_URL }}
          ecr-repository: ${{ vars.ECR_REPOSITORY }}
          ccq-ecr-repository: ${{ vars.CCQ_ECR_REPOSITORY }}
          nginx-ecr-repository: ${{ vars.NGINX_ECR_REPOSITORY }}
          kube-cert: ${{ secrets.KUBE_CERT }}
          kube-token: ${{ secrets.KUBE_TOKEN }}
          kube-cluster: ${{ secrets.KUBE_CLUSTER }}
          kube-namespace: ${{ secrets.KUBE_NAMESPACE }}
