name: Deploy to Environment

on:
  workflow_call:
    inputs:
      app-environment:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to ${{ inputs.app-environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.app-environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Deploy
        uses: ./.github/actions/deploy
        env:
          # This block only contains secrets being used as pod
          # environment variables. Anything used by the workflow
          # should be an input.
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          SESSION_ENCRYPTION_KEY: ${{ secrets.SESSION_ENCRYPTION_KEY }}
        with:
          app-environment: ${{ inputs.app-environment }}
          ecr-repository: ${{ vars.ECR_REPOSITORY }}
          ecr-registry_url: ${{ secrets.ECR_REGISTRY_URL }}
          kube-cert: ${{ secrets.KUBE_CERT }}
          kube-token: ${{ secrets.KUBE_TOKEN }}
          kube-cluster: ${{ secrets.KUBE_CLUSTER }}
          kube-namespace: ${{ secrets.KUBE_NAMESPACE }}
