name: Mocha Unit tests
on:
  workflow_dispatch: # Allow manual triggering only
  workflow_call: # Allow this workflow to be called by other workflows
    inputs:
      sha:
        description: "Commit SHA to check out"
        type: string
        default: ''

jobs:
  mocha-unit-tests:
    name: Mocha Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Setup Node and Dependencies
        uses: ./.github/actions/setup-node

      - name: Set env vars from values
        run: |
          yq '.rcw.env | to_entries[] | .key + "=" + (.value | tostring)' \
            ./deploy/laa-record-controlled-work/values.yaml >> $GITHUB_ENV

      - name: Run Mocha unit tests & c8 code coverage
        run: yarn c8 yarn test:unit --check-coverage
        env:
          CI: true
          NODE_ENV: "test"
          SESSION_SECRET: "mocha-test-secret"
          SESSION_ENCRYPTION_KEY: "mocha-test-encryption-key"

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: code-coverage-report
          path: coverage/