# Workflow: SCA ⚡️
# Description:
#   Scheduled and on-demand Security Composition Analysis run.
#   - Triggers: daily cron, pull/ push to main, workflow dispatch, branch protection rule.
#   - Environment and timezone shared across jobs.
# Jobs:
#   - setup: Prepares environment metadata.
#   - sca: Checks out repo, installs node, runs npm ci, executes ministryofjustice/sca action with dependency review configuration.

name: SCA ⚡️
run-name: Software Composition Analysis ⚡️

on:
  schedule:
    - cron: "0 0 * * *"

  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

  workflow_dispatch:
  branch_protection_rule:

permissions: {}

jobs:
  sca:
    name: Software Composition Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write
      pull-requests: write
      issues: write
      security-events: write
      actions: read

    steps:
      - name: Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: ⚡️ SCA
        uses: ministryofjustice/devsecops-actions/sca@234ac1dca7bb965417bae451d3ea284a1286d68c # v1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # Container Scanning
          docker-images-file: "docker-images.json"

          # Dependency Management
          renovate: "true"
          # renovate-version: "43.31.1"
          node_version: "25.6.1"

          # Custom Configurations
          dependency-review-config-file: ".github/config/dependency-review.yml"
          # trufflehog-config-file: ".github/config/trufflehog-config.yml"
          codeql-config-file: ".github/config/codeql.yml"
          codeql-upload-findings: "always"
          # codeql-languages: "javascript,typescript"
          # dependency-check-suppression-file: "dependency-check-suppression.xml"
