name: Snyk Infrastructure as Code

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snyk:
    name: Infra Scan
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # for github/codeql-action/upload-sarif to get workflow run info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5

      - name: Render Helm templates
        run: |
          mkdir rendered-templates
          for env in uat staging production; do
            helm template deploy/laa-record-controlled-work \
              -f deploy/laa-record-controlled-work/values/${env}.yaml \
              > rendered-templates/${env}.yaml
          done

      - name: Run Snyk to check Helm manifests for security issues
        continue-on-error: true
        uses: snyk/actions/iac@9adf32b1121593767fc3c057af55b55db032dc04 # v1.0.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: rendered-templates/

      - name: Upload deploy results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@5595ccaf912efad79be6eef63a5619ff05969be3 # v4
        with:
          sarif_file: snyk.sarif
          category: snyk-infrastructure

      - name: Upload rendered templates for inspection
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: rendered-templates
          path: rendered-templates/
